language: python
python:
- 3.6
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
   - pip install coveralls
script:
- python -m unittest
- python setup.py sdist bdist_wheel
- coverage run --source=tests setup.py test
deploy:
  provider: pypi
  user: mitiku
  password:
    secure: DkuiLggDPLZqCzUyTD9jQu+pLlG3AAW7FZtXTBc3rtgS2H1Yb5iv0zera6lAR4suITOndPKiggbMWSWzbFmvGikmEpH0yIqMMg+6/q2b8w9dERKi+vw3slkh4jubyE6mH4Nj/vKjdw8C7UdsqUMLZbgg0RECPWwUBbTPYXyvMli1KJXw+DRVwy7mIZrPNYZtlYBjmaXGLyPfncvarOhgDh0yt9BfOHTfg3vkd1ddABMAsilMUmZyIaTHQv2bg0O3ztZ7XFxV+t5eHMUcYS+XJO90FBU8cZXOlB5hOkXf723PdlSxXWFHuOnOxeXv2fE613LpdbmgkZ3D+I2Z0yDHlvq1SbkOEMPmS+IVBn/9fMpgBWui0KIpron68s4iVTtuoWkeyT8N+B4vmH3ur1HGbE8gnNdBN1mwbIVSBI1CC5D1oj6WB/CAnXucTwcyYeRhrFtaIgPg3Hq0+AQmvI+JWaHGiFjGRRFUR0rZwX9eVx76rTomobDC6XOI84YktrSUwPlTDAd1czJPZBkhbD5NRRzWDf2gCj9YqH0YB8ZQW3hVM5AHmeR2IZpYtvK2aAOnmIyTuUIWQ+dh2rirh5hrof+gnn4rX8wz7ZuFFwnFfR1DMEowlEfyYttmylA36QJ8KzBwJcGjC9aKixBJ7jo4XVzYH4zwNM5q7IyQtIyt4xg=
after_success:
  - coveralls