language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# # command to run tests, e.g. python setup.py test
script:  
  - python -m unittest
  - python setup.py sdist bdist_wheel
 
